/**
 * Split-panel chrome aligned with Users management (hero strip, list cards, empty state).
 */
export const adminSplitChrome = {
  leftPanel: {
    backgroundColor: '#fff',
    borderRadius: 16,
    border: '1px solid #E5E7EB',
    padding: 0,
    overflow: 'hidden',
    boxShadow: '0 4px 24px rgba(15, 23, 42, 0.06)',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: 'calc(100vh - 200px)',
  },
  heroStrip: {
    background: 'linear-gradient(135deg, #1e3a8a 0%, #5b21b6 45%, #7c3aed 100%)',
    color: '#fff',
    padding: '18px 18px 16px',
  },
  heroTitle: {margin: 0, fontSize: 15, fontWeight: 700, letterSpacing: '-0.02em'},
  heroStats: {display: 'flex', gap: 10, marginTop: 10, flexWrap: 'wrap'},
  heroChip: {
    background: 'rgba(255,255,255,0.14)',
    border: '1px solid rgba(255,255,255,0.22)',
    borderRadius: 999,
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 600,
  },
  searchBlock: {padding: 14, borderBottom: '1px solid #F1F5F9', background: '#FAFBFC'},
  toolbarBelowSearch: {
    padding: '12px 14px',
    borderBottom: '1px solid #F1F5F9',
    background: '#FAFBFC',
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  searchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    border: '1px solid #E2E8F0',
    borderRadius: 12,
    padding: '0 12px',
    background: '#fff',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
  },
  searchIcon: {fontSize: 15, opacity: 0.45, flexShrink: 0},
  searchInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    padding: '11px 0',
    fontSize: 14,
    background: 'transparent',
  },
  listWrap: {
    flex: 1,
    overflowY: 'auto',
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minHeight: 200,
  },
  userRow: (selected) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 12px',
    borderRadius: 14,
    border: selected ? '1px solid #A78BFA' : '1px solid #EEF2F7',
    background: selected ? 'linear-gradient(135deg, #f5f3ff 0%, #eef2ff 100%)' : '#fff',
    boxShadow: selected ? '0 4px 14px rgba(124, 58, 237, 0.12)' : '0 1px 3px rgba(15, 23, 42, 0.04)',
    cursor: 'pointer',
    transition: 'border-color 0.15s, box-shadow 0.15s',
  }),
  avatar: (hue) => ({
    width: 44,
    height: 44,
    borderRadius: 14,
    flexShrink: 0,
    display: 'grid',
    placeItems: 'center',
    fontWeight: 800,
    fontSize: 14,
    color: '#fff',
    background: `linear-gradient(135deg, hsl(${hue}, 70%, 46%), hsl(${(hue + 40) % 360}, 65%, 42%))`,
    boxShadow: '0 4px 12px rgba(15, 23, 42, 0.12)',
  }),
  rowMain: {minWidth: 0, flex: 1},
  rowName: {
    fontWeight: 700,
    fontSize: 14,
    color: '#0F172A',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  rowEmail: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  rowMeta: {display: 'flex', gap: 8, marginTop: 6, flexWrap: 'wrap'},
  tinyBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 6,
    background: '#F1F5F9',
    color: '#475569',
  },
  suspendedBadge: {
    fontSize: 11,
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: 6,
    background: '#FEF2F2',
    color: '#B91C1C',
    border: '1px solid #FECACA',
  },
  rightPanel: {
    backgroundColor: '#fff',
    borderRadius: 16,
    border: '1px solid #E5E7EB',
    padding: 0,
    overflow: 'hidden',
    boxShadow: '0 4px 24px rgba(15, 23, 42, 0.06)',
    minHeight: 420,
    display: 'flex',
    flexDirection: 'column',
  },
  emptyDetail: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 48,
    textAlign: 'center',
    color: '#64748B',
    background: 'linear-gradient(180deg, #FAFBFC 0%, #fff 100%)',
  },
  /** Cột nội dung căn giữa — tránh grid/flex stretch làm khối icon bị kéo ngang */
  emptyDetailInner: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: 320,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    minWidth: 72,
    maxWidth: 72,
    minHeight: 72,
    maxHeight: 72,
    boxSizing: 'border-box',
    flexShrink: 0,
    aspectRatio: '1',
    borderRadius: 20,
    background: 'linear-gradient(135deg, #EEF2FF, #F5F3FF)',
    border: '1px solid #E9D5FF',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 16,
  },
  emptyIconHead: {
    width: 22,
    height: 22,
    minWidth: 22,
    minHeight: 22,
    flexShrink: 0,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #A78BFA, #7C3AED)',
    opacity: 0.9,
  },
  emptyIconBody: {
    width: 38,
    height: 18,
    minWidth: 38,
    flexShrink: 0,
    borderRadius: 12,
    background: 'linear-gradient(135deg, #C4B5FD, #8B5CF6)',
    opacity: 0.85,
  },
  detailScroll: {flex: 1, overflowY: 'auto'},
  detailHead: {
    padding: '20px 22px 16px',
    borderBottom: '1px solid #EEF2F7',
    background: 'linear-gradient(180deg, #f8fafc 0%, #ffffff 100%)',
  },
  detailHeadTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 800,
    color: '#0F172A',
    letterSpacing: '-0.03em',
  },
  detailHeadSub: {margin: '8px 0 0', fontSize: 13, color: '#64748B', lineHeight: 1.45},
  profileHero: {
    background: 'linear-gradient(135deg, #0f172a 0%, #312e81 55%, #4c1d95 100%)',
    color: '#fff',
    padding: '24px 22px 22px',
  },
  profileTop: {display: 'flex', gap: 16, alignItems: 'flex-start'},
  avatarLg: (hue) => ({
    width: 72,
    height: 72,
    borderRadius: 20,
    flexShrink: 0,
    display: 'grid',
    placeItems: 'center',
    fontWeight: 800,
    fontSize: 26,
    color: '#fff',
    background: `linear-gradient(135deg, hsl(${hue}, 72%, 52%), hsl(${(hue + 35) % 360}, 68%, 48%))`,
    boxShadow: '0 12px 28px rgba(0,0,0,0.25)',
    border: '2px solid rgba(255,255,255,0.2)',
  }),
  profileName: {margin: 0, fontSize: 22, fontWeight: 800, letterSpacing: '-0.03em'},
  profileEmail: {margin: '6px 0 0', fontSize: 13, opacity: 0.88, wordBreak: 'break-all'},
  badgeRow: {display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 14},
  badge: (variant) => {
    const v =
      variant === 'danger'
        ? {bg: 'rgba(239,68,68,0.2)', br: 'rgba(248,113,113,0.45)'}
        : variant === 'ok'
          ? {bg: 'rgba(34,197,94,0.2)', br: 'rgba(74,222,128,0.45)'}
          : {bg: 'rgba(148,163,184,0.2)', br: 'rgba(203,213,225,0.4)'};
    return {
      fontSize: 11,
      fontWeight: 700,
      textTransform: 'uppercase',
      letterSpacing: '0.04em',
      padding: '5px 10px',
      borderRadius: 8,
      background: v.bg,
      border: `1px solid ${v.br}`,
    };
  },
  statGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: 12,
    padding: 18,
    background: '#F8FAFC',
    borderBottom: '1px solid #EEF2F7',
  },
  statCard: {
    background: '#fff',
    borderRadius: 14,
    padding: '14px 14px 12px',
    border: '1px solid #EEF2F7',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)',
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  statValue: {
    marginTop: 6,
    fontSize: 22,
    fontWeight: 800,
    color: '#0F172A',
    letterSpacing: '-0.02em',
  },
  statHint: {marginTop: 4, fontSize: 11, color: '#94A3B8'},
  section: {padding: '18px 20px'},
  sectionTitle: {
    margin: '0 0 12px',
    fontSize: 12,
    fontWeight: 800,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  infoGrid: {
    display: 'grid',
    gap: 0,
    borderRadius: 12,
    overflow: 'hidden',
    border: '1px solid #EEF2F7',
  },
  infoRow: (i) => ({
    display: 'grid',
    gridTemplateColumns: '140px 1fr',
    gap: 12,
    padding: '12px 14px',
    fontSize: 13,
    background: i % 2 === 0 ? '#FAFBFC' : '#fff',
    borderBottom: '1px solid #F1F5F9',
  }),
  infoLabel: {color: '#64748B', fontWeight: 600},
  infoValue: {color: '#0F172A', wordBreak: 'break-word'},
  dangerZone: {
    margin: '0 20px 20px',
    padding: 16,
    borderRadius: 14,
    border: '1px dashed #FECACA',
    background: 'linear-gradient(180deg, #FEF2F2 0%, #FFF 100%)',
  },
  dangerTitle: {
    margin: '0 0 8px',
    fontSize: 12,
    fontWeight: 800,
    color: '#991B1B',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  dangerText: {margin: '0 0 12px', fontSize: 13, color: '#7F1D1D', lineHeight: 1.5},
};
