import {StyleSheet, Platform} from 'react-native';
import {COLORS} from '../../constants';

/** Màu theo mock Admin Dashboard (xanh / tím / lá / cam) */
export const ADMIN_DASHBOARD = {
  BLUE: '#2169FF',
  BLUE_SOFT: '#E8F0FF',
  PURPLE: '#A033FF',
  PURPLE_SOFT: '#F3E8FF',
  GREEN: '#00B74A',
  GREEN_SOFT: '#E6F9EE',
  ORANGE: '#FF5E00',
  ORANGE_SOFT: '#FFF0E6',
  GRADIENT_START: '#2169FF',
  GRADIENT_MID: '#6B2FD4',
  GRADIENT_END: '#A033FF',
  TAB_INACTIVE_BG: 'rgba(255,255,255,0.22)',
};

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  android: {elevation: 4},
  default: {},
});

export const adminStyles = StyleSheet.create({
  screenBg: {flex: 1, backgroundColor: COLORS.BACKGROUND},
  scroll: {flex: 1},
  scrollContent: {paddingBottom: 32},
  hero: {
    backgroundColor: COLORS.PRIMARY,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    position: 'relative',
  },
  heroBackBtn: {
    position: 'absolute',
    zIndex: 2,
    padding: 8,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 6,
  },
  heroSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
    lineHeight: 20,
  },
  body: {paddingHorizontal: 16, paddingTop: 16},
  menuGrid: {gap: 12},
  menuCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.BACKGROUND_WHITE,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  menuIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.PRIMARY_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  menuTextWrap: {flex: 1},
  menuTitle: {fontSize: 16, fontWeight: '700', color: COLORS.TEXT},
  menuSubtitle: {fontSize: 13, color: COLORS.TEXT_SECONDARY, marginTop: 2},
  card: {
    backgroundColor: COLORS.BACKGROUND_WHITE,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    padding: 14,
    marginBottom: 12,
  },
  cardTitle: {fontSize: 16, fontWeight: '700', color: COLORS.TEXT, marginBottom: 10},
  hintText: {
    fontSize: 12,
    color: COLORS.TEXT_SECONDARY,
    marginBottom: 10,
    lineHeight: 18,
  },
  hintMono: {fontFamily: 'monospace', fontSize: 11, color: COLORS.TEXT},
  input: {
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: COLORS.TEXT,
    marginBottom: 8,
    backgroundColor: COLORS.BACKGROUND_WHITE,
  },
  row: {flexDirection: 'row', gap: 8},
  halfInput: {flex: 1},
  primaryButton: {
    marginTop: 4,
    backgroundColor: COLORS.PRIMARY_DARK,
    borderRadius: 10,
    alignItems: 'center',
    paddingVertical: 12,
  },
  primaryButtonText: {color: '#FFFFFF', fontWeight: '600'},
  secondaryButton: {
    marginTop: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_DARK,
    borderRadius: 10,
    alignItems: 'center',
    paddingVertical: 11,
    backgroundColor: COLORS.BACKGROUND_WHITE,
  },
  secondaryButtonText: {color: COLORS.PRIMARY_DARK, fontWeight: '600'},
  linkText: {fontSize: 13, color: COLORS.PRIMARY_DARK, fontWeight: '600'},
  emptyText: {fontSize: 13, color: COLORS.TEXT_SECONDARY},
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  topicRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER,
  },
  topicText: {fontSize: 13, color: COLORS.TEXT, flex: 1, paddingRight: 8},
  deleteText: {fontSize: 13, color: COLORS.ERROR, fontWeight: '600'},
  userRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  userLabel: {fontSize: 12, color: COLORS.TEXT_SECONDARY, marginBottom: 2},
  userValue: {fontSize: 14, color: COLORS.TEXT, fontWeight: '600'},
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.PRIMARY_SOFT,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 8,
  },
  badgeText: {fontSize: 12, fontWeight: '700', color: COLORS.PRIMARY_DARK},

  dashRoot: {flex: 1, backgroundColor: COLORS.BACKGROUND},
  dashGradient: {
    paddingTop: 22,
    paddingBottom: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
  },
  dashHeaderTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingTop: 4,
  },
  dashIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  dashSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.92)',
    marginTop: 0,
    lineHeight: 20,
    paddingHorizontal: 12,
  },
  dashTabScroll: {marginTop: 18, paddingLeft: 12},
  dashTabRow: {flexDirection: 'row', alignItems: 'center', paddingRight: 16, gap: 10},
  dashTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    gap: 8,
  },
  dashTabActive: {
    backgroundColor: '#FFFFFF',
  },
  dashTabInactive: {
    backgroundColor: ADMIN_DASHBOARD.TAB_INACTIVE_BG,
  },
  dashTabLabelActive: {fontSize: 14, fontWeight: '700', color: ADMIN_DASHBOARD.BLUE},
  dashTabLabelInactive: {fontSize: 14, fontWeight: '600', color: '#FFFFFF'},
  dashScrollHint: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginHorizontal: 16,
    gap: 8,
  },
  dashScrollTrack: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  dashBody: {paddingHorizontal: 16, paddingTop: 20},
  dashStatsRow: {flexDirection: 'row', gap: 12, marginBottom: 12},
  dashStatCard: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORS.BACKGROUND_WHITE,
    borderRadius: 16,
    padding: 16,
    ...cardShadow,
  },
  dashStatTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  dashStatIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashStatBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  dashStatBadgeText: {fontSize: 11, fontWeight: '700'},
  dashStatValue: {fontSize: 26, fontWeight: '800', color: COLORS.TEXT, letterSpacing: -0.5},
  dashStatLabel: {fontSize: 13, color: COLORS.TEXT_SECONDARY, marginTop: 4, fontWeight: '500'},
  dashSectionCard: {
    backgroundColor: COLORS.BACKGROUND_WHITE,
    borderRadius: 20,
    padding: 18,
    marginTop: 20,
    ...cardShadow,
  },
  dashSectionTitle: {fontSize: 17, fontWeight: '800', color: COLORS.TEXT, marginBottom: 16},
  dashQuickRow: {flexDirection: 'row', gap: 12, marginBottom: 12},
  dashQuickBtn: {
    flex: 1,
    minWidth: 0,
    borderRadius: 16,
    paddingVertical: 22,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 108,
  },
  dashQuickIcon: {marginBottom: 8},
  dashQuickLabel: {color: '#FFFFFF', fontSize: 13, fontWeight: '700', textAlign: 'center', paddingHorizontal: 4},
  dashQuickHint: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 4,
    paddingHorizontal: 6,
    lineHeight: 14,
  },
  dashQuickFooterLink: {
    marginTop: 14,
    alignItems: 'center',
    paddingVertical: 8,
  },
  dashQuickFooterLinkText: {fontSize: 13, fontWeight: '600', color: COLORS.TEXT_SECONDARY},
  dashContentLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  dashContentLinkLast: {borderBottomWidth: 0},
});
